#!/bin/bash
scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
source $scriptDir'/../lib/lib'

prompt_cmd() {
  DATETIME_1="$(short_datetime)"
  LINE_1="$(rgb_bg_ps1 $palette_primary)  $(no_color_ps1) $(rgb_fg_ps1 $palette_primary)$(current_user)$(rgb_fg_ps1 $palette_accent) >> $(rgb_fg_ps1 $palette_secondary)$(basename $PWD) "
  LINE_2="$(rgb_bg_ps1 $palette_primary)  $(no_color_ps1) $(rgb_fg_ps1 $palette_primary)$(short_date) $(rgb_fg_ps1 $palette_primary_dark)$(short_time) $(rgb_fg_ps1 $palette_accent)λ $(no_color_ps1)"

  PS1="\r\n${LINE_1}\r\n${LINE_2}"
}
if [[ "$TRANSIENT_PROMPT" == "1" ]]; then
    PS0='\[$(deleteprompt)\]\$ $(lastcommand)\n\[${PS1:0:$((EXPS0=1,0))}\]'
    export PROMPT_COMMAND='[ "$EXPS0" = 0 ] && deleteprompt && echo -e "\$" || EXPS0=0; prompt_cmd'
else
  export PROMPT_COMMAND='prompt_cmd'
fi
